# Generated by Django 4.1.2 on 2022-10-11 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'custom_user', 'verbose_name_plural': 'custom_users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 13, 0, 31, 968683, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 13, 0, 31, 969122, tzinfo=datetime.timezone.utc)),
        ),
    ]
